"""change locate to seoul

Revision ID: 04df921c7c95
Revises: 26af8c7147b5
Create Date: 2025-07-03 17:01:18.872004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04df921c7c95'
down_revision: Union[str, Sequence[str], None] = '26af8c7147b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "UPDATE items SET located = 'seoul' WHERE located IS NULL;"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute(
    #     "UPDATE items SET located = 'NULL' WHERE located = 'seoul';"
    # )
    pass
    # ### end Alembic commands ###
