"""add located to Item 

Revision ID: 26af8c7147b5
Revises: f4a47466ac79
Create Date: 2025-07-03 16:59:12.782267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26af8c7147b5'
down_revision: Union[str, Sequence[str], None] = 'f4a47466ac79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('located', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'located')
    # ### end Alembic commands ###
